site_name: Self-Organizing-Recurrent-Network-Simulator
site_url: ""
site_description: Project documentation with Markdown.
site_author: Marius Vieth

repo_url: https://github.com/gitmv/Self-Organizing-Recurrent-Network-Simulator
edit_uri: ""

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

nav:
    - Home: index.md
    - Introduction:
        - PIP installation: Introduction/PIP_installation.md
        - Manual installation: Introduction/Manual_installation.md
    - Tutorials:
        - Basics: Tutorials/basics.md
        - Synapses and Input: Tutorials/Synapses_and_Input.md
        - User Interface: Tutorials/User_Interface.md
    - Examples:
        - Differential Equation: Examples/Differential_Equation.md
        - Tensorflow: Examples/Tensorflow.md

plugins:
    - search